Actual date
dec - 11
jan 26


Reschedule  Date
dec- 04
jan-


scholarship - $37,728
Fees        - $15,231
Loan        - $18,000
Dept        - $ 1,000
Sunil       - $ 5,642
sahana      - $ 7,200
-----------------------
Total       - $47,000
-----------------------