@startuml
left to right direction

actor Librarian
boundary BookCatalogUI
control BookCatalogController
entity Book

Librarian --> BookCatalogUI
BookCatalogUI --> BookCatalogController
BookCatalogController --> Book

@enduml
